typography_spectrum: 0.7946636818815023
color:
  brandColors:
    - '#ffffff'
    - '#61c2a1'
    - '#d7efe7'
    - '#7ecdb2'
    - '#b8e3d1'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6223214366473258
analytics:
  google: null
  facebook: null
  twitter: null
name: Nicole Marie Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Design is all around you
purpose: []
