name: Nicole Marie Design
favicon: null
layout_spectrum: 0.6223214366473258
typography_spectrum: 0.7946636818815023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.04093737085349858
  lightness: 0.027158636366948485
  saturation: 0.03904892550781369
  rhythmicContrast: 0.5178101346828043
purpose: []
